chainguard-dev/rules_apko

- apko/private/versions.bzl
I'm currently experiencing this error when I tried setting up `rules_apko` locally. 
```
ERROR: User/Dev/bazel-monorepo/WORKSPACE.bazel:487:25: fetching apko_repositories rule //external:apko_darwin_arm64: Traceback (most recent call last):
File "/private/var/tmp/_bazel_user/82451c28c0803a6357e2fc0181c91a49/external/rules_apko/apko/repositories.bzl", line 56, column 40, in _apko_repo_impl
repository_ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/thesayyn/apko/releases/download/v0.0.0/apko_0.0.0_darwin_arm64.tar.gz] to /private/var/tmp/_bazel_User/82451c28c0803a6357e2fc0181c91a49/external/apko_darwin_arm64/temp13831384609312796342/apko_0.0.0_darwin_arm64.tar.gz: Checksum was …
```
> chore: update apko shas for v0.0.0

- e2e/smoke/README.md
- e2e/smoke/apko.resolved.json
- e2e/smoke/apko.yaml
- examples/lock/apko.resolved.json
- examples/lock/apko.yaml
- examples/multi_arch_and_repo/apko.resolved.json
- examples/multi_arch_and_repo/apko.yaml
- examples/oci/apko.resolved.json
- examples/resolve.sh
- examples/wolfi-base/apko.resolved.json
Do not depend on the alpine/edge (as resolved artifacts are dangling).
Instead depend on the stable `v3.18`.
In general it's a bad practice when `bazel test //...` brakes because someone else (periodic) actions.
The same problem applies to Wolfi... (without artifacts cache).
After this PR: `bazel test //...` works.
> Do not depend on the alpine/edge (as resolved artifacts are dangling).

- apko/private/apko_image.bzl
- apko/private/apko_run.bzl
- e2e/smoke/BUILD
- e2e/smoke/apko.generated.lock.json
- examples/multi_arch_and_repo/apko.lock.json
Before this change, the `apko.yaml` config file of the image had to be in the source code directory.
With this change it can be output of some bazel rule. 
Generated lockfile is still outputted to source code directory.
> Make `.lock` rule work when passing `config` to `apko_image` as label to generated target.

- apko/private/toolchains_repo.bzl
Fix https://github.com/chainguard-dev/rules_apko/issues/70
> Fix linux_386 platform at toolchains_repo.bzl

- .github/workflows/ci.yaml
- apko/private/toolchains_repo.bzl
- apko/repositories.bzl
- e2e/smoke/apko.lock.json
- e2e/smoke/multifile_config/apko.generated.lock.json
- examples/lock/apko.lock.json
- examples/multi_arch_and_repo/apko.lock.json
- examples/oci/apko.lock.json
- examples/wolfi-base/apko.lock.json
- scripts/update_locks.sh
The motivation here is to be able to use newest apko releases without updating rules_apko as an intermediate step.
It offloads some complexity (specifying hash, prefix to strip and url to the user), but if one just wants to use default apko version, they don't need to do it.
> Allow users to provide the versions of apko binaries not listed in versions.bzl

- .github/dependabot.yml
- .github/workflows/ci.yaml
- .github/workflows/release.yml
- examples/multi_arch_and_repo/apko.lock.json
- examples/multi_arch_and_repo/apko.yaml
- examples/multi_arch_and_repo/test.yaml
This PR implements best practices around GitHub Actions hardening including:
- Pinning Actions to digests
- Adding `dependabot.yml` configuration to keep Actions updated
- Scoping the GitHub token permissions appropriately (read-only except for the `release.yml` Workflow)
- The `release.yml` Workflow calls a reusable Workflow so we can't add the hardening Action as a step to this job
Two of the matrix tests were failing because of an issue locating `libcurl~8.5.0` so I fixed those as well.
> Harden GHA Workflows

- apko/private/apko_lock.bzl
Executables should refer to runfiles with short paths.
> Fix path to apko binary in apko_lock.

- .bcr/presubmit.yml
There were errors on Bazel Central Registry because the credential helpers workaround requires setup. Bazel 7 has correct support for Range headers, and is the LTS version.
> Stop testing on Bazel 6

- apko/private/apko_run.bzl
In https://github.com/sourcegraph/sourcegraph, we've [defined our own apko toolchain](https://github.com/sourcegraph/sourcegraph/pull/60785/files#diff-7fc57714ef13c3325ce2a1130202edced92fcccc0c6db34a72f7b57f60d552a3R350-R356) to integrate a patch to [go-apk](https://github.com/chainguard-dev/go-apk/pull/216) for the apko binary. Due to this, we pass `register = False` to `apko_register_toolchains`. 
This surfaced a correctness issue when trying to run `bazel run @rules_apko//apko`, with the following error:
```
INFO: Running command line: bazel-bin/external/rules_apko/apko/_apko_run.sh
Workdir: /home/noah/Sourcegraph/sourcegraph
/home/noah/.cache/bazel/_bazel_noah/8fd1d20666a46767e7f29541678514a0/execroot/__main__/bazel-out/k8-fastbuild/bin/external/rules_apko/apko/_apko_run.sh: line 11: …
```
> pass correct apko binary runfiles path to apko_run launcher

- apko/private/apko_lock.bzl
- docs/rules.md
- docs/translate_lock.md
- e2e/smoke/multifile_config/BUILD
The original reason was to enables passing: '--ignore-signatures' due to problems with artifactory support for rsa keys.
But this also brings consistency with apko_build.
> Allow specyfying 'args' for apko_lock.

- .github/workflows/ci.yaml
Drop tests on windows & macosx, as some of the CI steps expect native
linux execution capabilities, and are now failing.
> Drop tests on windows and macosx, unsupported

- .bazelversion
- .github/workflows/ci.yaml
Upgrade CI to latest releases of bazel 6 and 7.
Note 7.6.1 support was tested separately in:
- https://github.com/chainguard-dev/rules_apko/pull/125
Somebody with powers needs to lift 7.1.0 as a required check.
> Upgrade to latest bazel 6 and 7

- .github/workflows/release.yml
Release workflow wants more permissions:
```
Invalid workflow file: .github/workflows/release.yml#L15
The workflow is not valid. .github/workflows/release.yml (Line: 15, Col: 3): Error calling workflow 'bazel-contrib/.github/.github/workflows/release_ruleset.yaml@9ed8d86404ac3214f80cfb02e49f44a1b28b17b0'. The nested job 'attest' is requesting 'attestations: write, id-token: write', but is only allowed 'attestations: none, id-token: none'.
```
Seems like it wants to attest itself.
> release workflow permissions

- apko/private/apko_lock.bzl
- apko/private/apko_run.bzl
Also remove leading newline from LAUNCHER_TEMPLATE other examples of
such wrappers do not have a leading newline.
Reference example is https://github.com/bazel-contrib/rules_jvm_external/blob/d8af22108bd8b353a226140570008231f2921931/private/rules/maven_publish.bzl#L12
> Remove leading newline from launcher template

- .bcr/presubmit.yml
Support for bazel 8 was added, and support for macos dropped. Plus
upgrade platfroms to newer debian and ubuntu releases.
Maybe this was blocking release to bcr.
> bcr: update presubmit

- .github/workflows/ci.yaml
I expected this to fail, but CI passes.
I guess we don't require or need work spaces after-all?
Fixes: #159
> tests: stop using workspaces for tests

- .github/workflows/release.yaml
Fixup to use reusable workflow correctly, as it must be a separate
job.
> github: Fix usage of reusable workflows

- .github/workflows/release.yaml
Use best practice to scope permissions on per-job basis.
> github: use permissions scoped to the job

- .github/workflows/release.yaml
The tag action actually has a different output name:
- https://github.com/chainguard-dev/actions/blob/8fa93a69e091d35d496b4af0a32d2e79c8d1ce00/git-tag/action.yml#L47
The git-tag action output is git_tag.
I really really want github workflow validation of template variables.
> github: correct steps output name

- .bcr/config.yml
- .bcr/source.template.json
- .github/workflows/release_prep.sh
- Drop no-op bcr/config.yml.
- Add docs to the template.json
- Drop obsolete / out-of-date release boilerplate
- Add docs in release_prep.sh
Based on recommendations from:
- https://github.com/chainguard-dev/rules_apko/pull/176
note this will remove repetitive boilerplate around obsolete workspace setup in every release notes.
> bcr: add docs
